//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMag.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lоft
    {
        public Lоft()
        {
            this.Reservations = new HashSet<Reservations>();
        }
    
        public int Id { get; set; }
        public int IdSubjectMatter { get; set; }
        public decimal PriceOneHour { get; set; }
    
        public virtual SubjectMattеr SubjectMattеr { get; set; }
        public virtual ICollection<Reservations> Reservations { get; set; }
    }
}
