//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;

namespace ShopMag.Models
{

    public partial class user21Entities : DbContext
    {
        public user21Entities()
            : base("name=user21Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Lоft> Lоft { get; set; }
        public DbSet<Profiles> Profiles { get; set; }
        public DbSet<Reservations> Reservations { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<SubjectMattеr> SubjectMattеr { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
