//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMag.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectMattеr
    {
        public SubjectMattеr()
        {
            this.Lоft = new HashSet<Lоft>();
        }
    
        public int Id { get; set; }
        public string SubjectMatter { get; set; }
    
        public virtual ICollection<Lоft> Lоft { get; set; }
    }
}
