//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace ShopMag.Models
{
    [Serializable]
    internal class UnintentionalCodeFirstException : Exception
    {
        public UnintentionalCodeFirstException()
        {
        }

        public UnintentionalCodeFirstException(string message) : base(message)
        {
        }

        public UnintentionalCodeFirstException(string message, Exception innerException) : base(message, innerException)
        {
        }

        protected UnintentionalCodeFirstException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }
}